apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: true
spec:
  containers:
  - name: node-js
    image: node
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: 8Gi
        cpu: "4"
      requests:
        memory: 4Gi
        cpu: "2"
    volumeMounts:
      - name: docker-socket
        mountPath: /var/run
  - name: python
    image: 3.8.13-bullseye
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    volumeMounts:
      - name: docker-socket
        mountPath: /var/run
  volumes:
  - name: docker-socket
    emptyDir: {}
  nodeSelector:
    jenkins-worker: "true"
  